project:
  type: website
  output-dir: docs

website:
  title: "Wade Sedgwick"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
<<<<<<< HEAD
=======
      - href: blog_post.qmd
>>>>>>> 71d80474df4a5e65770a4859f735efc6373332a2
      - href: posts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

