project:
  type: website
  output-dir: docs

website:
  title: "Wade Sedgwick"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: hello.qmd
      - href: blog_post.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

