project:
  type: website
  output-dir: docs

website:
  title: "wsedgwick.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - mystyles.scss
    mainfont: Silkscreen
    css: styles.css
    toc: true
    

editor: visual

